version: '3'
services:

  server:
#    build: ./server
#    image: tetianazubko/group19:latest
#    container_name: group19
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "mongodb"
    environment:
      - MONGODB_URI= mongodb://mongodb:27017/booksData
    ports:
    - "3000:3000"


  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    entrypoint:
      - MONGO_DATA_DIR=/data/db
    volumes:
    - ./data/:/data/db
    ports:
    - "27017:27017"
